---
- hosts: all
  become: yes
  tasks:

    - name: Add Jenkins apt repo key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    
    - name: Add Jenkins apt repo
      repo: https://pkg.jenkins.io/debian-stable
      state: present
      update_cache: yes
      filename: jenkins

    - name: Install JRE
      apt: 
        name: openjdk-11-jre
        state: present

    - name: Install Jenkins
      apt: 
       name: jenkins 
       state: installed
      notify:
      - restart jenkins
    
  handlers:
    - name: restart jenkins
      service: name=jenkins state=restarted