---
- hosts: all
  become: true
  tasks:

    - name: Add Jenkins apt repository key.
      ansible.builtin.get_url:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        dest: /etc/apt/trusted.gpg.d/jenkins.asc
        mode: '0644'
        force: true

    # - name: Add Jenkins apt repo key
    #   ansible.builtin.apt_key:
    #     url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    #     state: present

    - name: Add Jenkins apt repository.
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present
        update_cache: true

    - name: Install JRE
      ansible.builtin.apt:
        name: openjdk-11-jre
        state: present

    - name: Install requisite Python packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - pylint
          - python-pytest
          - python-venv
        state: present
        update_cache: true

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: true
      notify:
        - restart jenkins

  handlers:
    - name: restart jenkins
      ansible.builtin.service: name=jenkins state=restarted
